2022-04-27 15:00:21,419 INFO    MainThread:230081 [wandb_setup.py:_flush():69] setting env: {}
2022-04-27 15:00:21,419 INFO    MainThread:230081 [wandb_setup.py:_flush():69] setting login settings: {}
2022-04-27 15:00:21,419 INFO    MainThread:230081 [wandb_init.py:_log_setup():334] Logging user logs to /storage/scratch1/9/ahelbling6/oracle-guided-image-synthesis/auto_localization/experiments/morpho_mnist/wandb/run-20220427_150021-1q5wky1i/logs/debug.log
2022-04-27 15:00:21,419 INFO    MainThread:230081 [wandb_init.py:_log_setup():335] Logging internal logs to /storage/scratch1/9/ahelbling6/oracle-guided-image-synthesis/auto_localization/experiments/morpho_mnist/wandb/run-20220427_150021-1q5wky1i/logs/debug-internal.log
2022-04-27 15:00:21,419 INFO    MainThread:230081 [wandb_init.py:init():367] calling init triggers
2022-04-27 15:00:21,420 INFO    MainThread:230081 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'trials': 1, 'epochs': 50, 'lr': 0.001, 'batch_size': 256, 'trainer': 'triplet', 'weight_decay': 0.0, 'gamma': 0.999, 'optmizer_type': 'adam', 'lambda_warmup_epochs': 1, 'triplet_warm_start': 1, 'recon_warm_start': 1, 'recon_zero_start': 0, 'mcmv_sampling': False, 'group': 'test_004', 'localization_config': {'indexed': False, 'trials': 20, 'k': 1.0, 'localizer_type': 'BayesianTriplet', 'num_queries': 30, 'similarity_mode': True, 'similarity_dim': 6, 'normalization': 0, 'latent_dim': 6, 'maximum_likelihood_selection': False}, 'model_config': {'model_type': 'IsolatedVAE', 'latent_dim': 6, 'similarity_dim': 6, 'reconstructive_dim': 0, 'in_shape': 32, 'd': 32, 'layer_count': 4, 'channels': 1, 'loss_name': 'BayesianTripletLoss', 'sub_loss_type': 'isolated', 'masks': False, 'adam_beta_1': 0.9, 'adam_beta_2': 0.999, 'kl_beta': 0.01, 'recon_beta': 1.0, 'triplet_beta': 1.0, 'triplet_margin': 0.1, 'uncertainty_constant': False, 'similarity_batchnorm': False, 'triplet_mining': False, 'l2_normalization': False, 'attributes': [0, 1, 2, 3, 4, 5], 'component_weighting': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 'isotropic_variance': False, 'bce': True, 'gradient_clipping': False, 'indexed': True}, 'dataset_config': {'component_weighting': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 'attribute_return': True, 'which_digits': [1], 'one_two_ratio': 0.0, 'batch_size': 256, 'dataset_name': 'MorphoMNIST', 'indexed': True, 'num_workers': 6, 'single_feature_triplet': False, 'inject_triplet_noise': 0.0}}
2022-04-27 15:00:21,420 INFO    MainThread:230081 [wandb_init.py:init():416] starting backend
2022-04-27 15:00:21,420 INFO    MainThread:230081 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-27 15:00:21,423 INFO    MainThread:230081 [backend.py:ensure_launched():123] starting backend process...
2022-04-27 15:00:21,432 INFO    MainThread:230081 [backend.py:ensure_launched():128] started backend process with pid: 230301
2022-04-27 15:00:21,434 INFO    MainThread:230081 [wandb_init.py:init():421] backend started and connected
2022-04-27 15:00:21,435 INFO    MainThread:230081 [wandb_init.py:init():461] updated telemetry
2022-04-27 15:00:21,436 INFO    MainThread:230081 [wandb_init.py:init():480] communicating current version
2022-04-27 15:00:23,113 INFO    MainThread:230081 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.12.15 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-27 15:00:23,113 INFO    MainThread:230081 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2022-04-27 15:00:23,246 INFO    MainThread:230081 [wandb_init.py:init():518] starting run threads in backend
2022-04-27 15:00:27,944 INFO    MainThread:230081 [wandb_run.py:_console_start():1480] atexit reg
2022-04-27 15:00:27,945 INFO    MainThread:230081 [wandb_run.py:_redirect():1343] redirect: SettingsConsole.REDIRECT
2022-04-27 15:00:27,945 INFO    MainThread:230081 [wandb_run.py:_redirect():1348] Redirecting console.
2022-04-27 15:00:27,945 INFO    MainThread:230081 [redirect.py:install():213] install start
2022-04-27 15:00:27,946 INFO    MainThread:230081 [redirect.py:install():228] install stop
2022-04-27 15:00:27,946 INFO    MainThread:230081 [redirect.py:install():213] install start
2022-04-27 15:00:27,946 INFO    MainThread:230081 [redirect.py:install():228] install stop
2022-04-27 15:00:27,946 INFO    MainThread:230081 [wandb_run.py:_redirect():1394] Redirects installed.
2022-04-27 15:00:27,946 INFO    MainThread:230081 [wandb_init.py:init():542] run started, returning control to user process
2022-04-27 15:14:26,772 ERROR   stderr    :230081 [redirect.py:_pipe_relay():139] problem in pipe relay
Traceback (most recent call last):
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 137, in _pipe_relay
    cb(name, data)
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 187, in publish_output
    self._publish_output(o)
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 192, in _publish_output
    self._publish(rec)
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-04-27 15:14:44,207 INFO    MainThread:230081 [wandb_run.py:_atexit_cleanup():1450] got exitcode: 1
2022-04-27 15:14:44,208 INFO    MainThread:230081 [wandb_run.py:_restore():1422] restore
2022-04-27 15:14:44,208 INFO    MainThread:230081 [redirect.py:uninstall():232] uninstall start
2022-04-27 15:14:44,208 INFO    MainThread:230081 [redirect.py:_stop():287] _stop: stdout
2022-04-27 15:14:44,208 INFO    MainThread:230081 [redirect.py:_stop():293] _stop closed: stdout
2022-04-27 15:14:44,208 INFO    stdout    :230081 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2022-04-27 15:14:44,208 INFO    stdout    :230081 [redirect.py:_pipe_relay():145] relay done done: stdout
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:_stop():299] _stop joined: stdout
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:_stop():301] _stop rd closed: stdout
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:uninstall():236] uninstall done
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:uninstall():232] uninstall start
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:_stop():287] _stop: stderr
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:_stop():293] _stop closed: stderr
2022-04-27 15:14:44,209 INFO    stderr    :230081 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2022-04-27 15:14:44,209 INFO    stderr    :230081 [redirect.py:_pipe_relay():145] relay done done: stderr
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:_stop():299] _stop joined: stderr
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:_stop():301] _stop rd closed: stderr
2022-04-27 15:14:44,209 INFO    MainThread:230081 [redirect.py:uninstall():236] uninstall done
2022-04-27 15:14:49,754 ERROR   MainThread:230081 [wandb_run.py:_atexit_cleanup():1468] Problem finishing run
Traceback (most recent call last):
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1458, in _atexit_cleanup
    self._on_finish()
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1594, in _on_finish
    self.history._flush()
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 790, in _history_callback
    row, step, publish_step=not_using_tensorboard
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 222, in publish_history
    self._publish_history(history)
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 206, in _publish_history
    self._publish(rec)
  File "/storage/home/hcoda1/9/ahelbling6/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
